### ISSUE TITLE
Support for AN - Netherlands Antilles

### ISSUE THREAD

**Issue by kluku** [xvrh/common_locale_data#12]
Please add support for this ISO code:
https://www.iso.org/obp/ui/#iso:code:3166:AN

**Comment by arjanmels** [comment]
It's supported in my fork https://github.com/[arjanmels/common_locale_data](https://github.com/arjanmels/common_locale_data)
and I have pull requests lined up #11 to enable in this repo.

**Comment by arjanmels** [comment]
Is addressed in the latest released version (2.0.0)

**Comment by Dilavo** [comment]
@arjanmels is not working for me. Can you give me a example how to get name for iso code AN?
